### PR TITLE
Remove "How to be Stylish" page from golf example.

### PR DESCRIPTION
**Pull request by mlefoster**
The golf example is based off of Rustici Software's SCORM example courses. Recently, it came to light that the final page of the course (before the quiz) was better off removed from the example courses. The page in question was titled "How to be Stylish", and was dedicated to women and girls learning to
play golf, with text taken from WikiHow. Unfortunately, the article seemed to have a very condescending tone, and could have been interpreted to suggest that women don't know anything about sports or don't know how to take sports seriously.

Because the page could be read in such a negative light, it seemed inappropriate to include it in something that is being used as a promotional tool (either for Rustici Software or for xAPI evangelism more generally).

I tested the course afterwards, and the course still works correctly.

### CODE REVIEW

**Comment by brianjmiller** [comment]
Per offline discussion we have to think about whether or not this constitutes a new Activity, which corresponds to a new 'id', which ripple effects through the Registry, recipe, etc. It probably does in so far as the prototypes are supposed to represent a best practices example. But....

**Comment by garemoko** [comment]
IMHO and pretending that this is a real course on some company's LMS, it doesn't constitute a new activity unless the assessment is changed. There's no question relating to this in the assessment. 

*Why is the assessment so significant? All the other prototypes don''t even have assessments!*
Well, because this example is representative of a traditional e-learning course where in a lot of cases the assessment is the most significant bit. 

This could be a great use case for the context.revision property.

**Comment by mlefoster** [comment]
Is there anything I can do to push this forward? I would love to see this off of my "open PRs" list.

**Comment by mlefoster** [comment]
e.g., I could change the context.revision property if need be.

**Comment by brianjmiller** [comment]
Heh, probably not, short of convincing @tseabrooks this is more important than all the other work, including the other OSS lib stuff which includes more relevant PRs. If you want it off the list, I suppose you could close it :-).

**Comment by brianjmiller** [comment]
Mostly I disagree with this, but @mlefoster wants it gone, and I don't have the desire to fight it :-). If you care deeply about the golf prototype, realize you may be missing a statement you used to get (also, you shouldn't care deeply).

**Pull request merged**
