### PR TITLE
Update prototypes in line with emerging best practice

### PR DESCRIPTION
**Pull request by garemoko**
A number of changes including adding additional statements to help with duration tracking, updating verbs to take advantage of those in registry, making use of registration from the launch page and updating some legacy stuff from back as far as 0.9 (mbox as an array). 

It looks like the white space on line that I've added is not right, which I blame my editor for. I'm moving to Mac from Monday so will have a look at that from there.

### CODE REVIEW

**Comment by garemoko** [comment]
I need to update the Tetris level activity type to use http://curatr3.com/define/type/level which is an existing identifier for this purpose.

**Comment by brianjmiller** [comment]
This seems like a lot of whitespace for whitespace fixes. I'm not sure we want to go through and make a bunch of changes to code that hasn't been touched in a *very* long time. Like the statement issuer stuff or CSS files, etc. How hard would it be to boil this down to just the things that actually changed? Also the last comment in this PR indicates that it was pending TinCanJS PRs being merged, presumably that has occurred, but I don't see any corresponding bump in the submodules here. Is a newer version required? And if so need to get a submodule bump commit in here, presumably to most recent upstream master.

**Comment by garemoko** [comment]
I'll figure out how to bump the submodules tomorrow. 

On the whitespace, you'll see there's 3 commits on 9th December relating to this. I can try and do a separate PR without https://github.com/garemoko/TinCan_Prototypes/commit/70ee6db6920ace67c29be597c2862b9b9d0b3724 if you like. I should also be able to remove https://github.com/garemoko/TinCan_Prototypes/commit/c31dfde3d0561262c418d5c94575623c37e18311, but just bear in mind some of the newlines added my me will use tabs in that case.

**Comment by garemoko** [comment]
It doesn't look like there's a clean way to remove the whitespace fixes without causing conflicts. 

I'm not sure what the next step is here. Would it be helpful for me to provide a list of files that have changed outside of the whitespace fixes?

**Comment by garemoko** [comment]
Certainly I didn't touch the statement issuer and the CSS changes I made were only minor tweaks on the launch page .

**Comment by garemoko** [comment]
What if you were to review: https://github.com/garemoko/TinCan_Prototypes/compare/RusticiSoftware:master...b65340b1ff1633faa3080ec8e1139da868f0a6df (ignoring the use of tabs) and https://github.com/garemoko/TinCan_Prototypes/compare/garemoko:733a8a05d22c8a04ce1b172770b7e40c4f4e905e...2fcf9425980d1adb89101ed83dd2c49ce3a7671c . This skips over the whitespace changes so you can just see the code changes.

**Comment by brianjmiller** [comment]
Superseded by #30.

**Pull request closed without merging**
